# Generated by Django 5.2.1 on 2025-06-11 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_saved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='saved_by',
        ),
    ]
